/*
 * generated by Xtext
 */
package de.htwg.mdsd.xtext.portals.validation
import de.htwg.mdsd.xtext.portals.dsl.Bot
import java.util.List

import org.eclipse.xtext.validation.Check
import de.htwg.mdsd.xtext.portals.dsl.DslPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DslValidator extends AbstractDslValidator {

	@Check
	def checkColor(Bot bot) {
		var List<String> list = newArrayList
		list.add("blue")
		list.add("green")
		
		if (!list.contains(bot.color)) {
			error('Color is not available', DslPackage.Literals.BOT__COLOR)
		}
	}

}
