/*
 * generated by Xtext
 */
package de.htwg.mdsd.xtext.portals;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends de.htwg.mdsd.xtext.portals.AbstractDslRuntimeModule {

}
